### ISSUE TITLE
Support @client @export apollo directive

### ISSUE THREAD

**Issue by sscotth** [kamilkisiela/graphql-inspector#1608] opened 2020-07-24 05:57 UTC
**Describe the bug**

Does not handle [@client @export directive](https://github.com/apollographql/apollo-client/blob/master/docs/source/local-state/managing-state-with-field-policies.mdx#using-local-only-fields-as-graphql-variables)

**To Reproduce**

```graphql
query CurrentAuthorPostCount($authorId: Int!) {
  currentAuthorId @client @export(as: "authorId")
  postCount(authorId: $authorId)
}
```

```
error
in file.graphql:

 - Cannot query field currentAuthorId on type Query.
 - Unknown directive @export.
```

Also nested:

```graphql
query myPosts($authorId: Int!) {
  user @client {
    id @export(as: "authorId")
  }

  postCount(authorId: $authorId)
}
```

**Expected behavior**

Example text case:

```ts
// packages/core/__tests__/validate/apollo.ts

test('should handle @exported @client variables', () => {
  const schema = buildSchema(/* GraphQL */ `
    type Post {
      id: ID
      title: String
    }

    type Query {
      random(seed: Int): Int! // Client only
      post(id: ID!): Post     // Remote
    }
  `);

  const doc = parse(/* GraphQL */ `
    query getRandomPost($postId: Int!) {
      random @client @export(as: "postId")
      post(id: $postId) {
        id
        title
      }
    }
  `);

  const results = validate(schema, [new Source(print(doc))], {
    apollo: true,
  });

  expect(results).toHaveLength(0);
});
```

**Environment:**

- OS: macOS v10.15.6
- `@graphql-inspector/cli`: v2.1.0
- `graphql`: v15.3.0
- NodeJS: v14.6.0

**Comment by danielrearden** [comment] 2020-07-30 01:02
Hi @sscotth. Thanks for submitting an issue and for the example test case!

Unfortunately, I can't seem to reproduce the issue.  The above test actually passes for me. We strip any `@client` fields from the document before validating it. That includes nested exported fields as long as the parent field still has `@client` on it. The only way I can reproduce the issue is by omitting the `apollo` parameter (for example, by running the CLI command and omitting the `--apollo` flag). Here's a demo of the expected behavior in action: https://runkit.com/danielrearden/5f22193ba500c10013c57e8c

If you can provide additional debugging details or ideally a reproduction in the form of a Code Sandbox or repo, we can open this issue up again but I'm closing it for now.

**Closed by danielrearden** 2020-07-30 01:02 UTC
