### ISSUE TITLE
Docker image throwing unknown module exception

### ISSUE THREAD

**Issue by tylerdavis** [kamilkisiela/graphql-inspector#2141] opened 2022-07-15 23:11 UTC
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

Running the following command with the latest docker image version

```
graphql-inspector diff https://app.launchnotes.io/graphql frontend/src/data/schema.graphql
```

Results in the following exception:

```
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'tslib'
Require stack:
- /usr/local/share/graphql-inspector/cli/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:[27](https://gitlab.com/shiny-planes/the-goat/-/jobs/2729717131#L27))
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/share/graphql-inspector/cli/dist/index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:[32](https://gitlab.com/shiny-planes/the-goat/-/jobs/2729717131#L32))
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/share/graphql-inspector/cli/dist/index.js' ]
}
```

**To Reproduce**

```
graphql-inspector diff https://app.launchnotes.io/graphql frontend/src/data/schema.graphql
```

**Expected behavior**

I expect the diff to run successfully.

**Environment:**

- Latest docker image

**Additional context**

We have been running this in CI for about six months with no issue until the recent release pushed a new version to docker.  Since we're using the latest tag, builds after the release began to fail.

**Comment by spawnia** [comment] 2022-07-18 07:44
A single command to reproduce the same error is:

```sh
docker run --pull=always kamilkisiela/graphql-inspector:latest graphql-inspector
```

I already described this problem in https://github.com/kamilkisiela/graphql-inspector/pull/2035. The changes from there were merged in https://github.com/kamilkisiela/graphql-inspector/pull/2139 - unfortunately without fixing [the outstanding issue with it](https://github.com/kamilkisiela/graphql-inspector/pull/2035#discussion_r728762637).

I am not sure what is necessary to fix this, but I reckon that the build steps described in [Dockerfile](https://github.com/kamilkisiela/graphql-inspector/blob/master/Dockerfile) will have to be extended to include dependencies.

**Comment by keshav-1835i** [comment] 2022-07-19 03:47
Started breaking in our CI pipeline too :(

**Comment by HSTsou** [comment] 2022-07-19 06:41
Can provide the older version (v3.2.0) to docker hub to skip the failure from the v3.3.0 ?

**Comment by ayumitamai97** [comment] 2022-07-19 08:44
Yet unofficial, I pushed a modified Docker image based on v3.2.0.

Docker Hub: https://hub.docker.com/repository/docker/ayumitamai97/graphql-inspector
Changes: https://github.com/ayumitamai97/graphql-inspector/releases/tag/v3.2.0-modified

Example:

```
docker run --pull=always ayumitamai97/graphql-inspector:3.2.0-modified graphql-inspector introspect your_schema.graphql
```

**Comment by kemsar** [comment] 2022-07-19 21:17
Subscribing since I've run into the same issue.

**Comment by ayumitamai97** [comment] 2022-07-23 19:37
@spawnia @kamilkisiela Hi. I fixed this problem in this PR https://github.com/kamilkisiela/graphql-inspector/pull/2144. Could you please review it? Thanks :)

**Closed** 2022-08-23 15:13 UTC

**Comment by doriandekoning** [comment] 2022-08-24 08:10
@kamilkisiela  Would it be possible to tag a new version so we can use the tagged image? That would be amazing 🙏

**Comment by spawnia** [comment] 2022-08-24 09:14
The fixed version is currently only available under the tag `master`:

![image](https://user-images.githubusercontent.com/12158000/186380028-9618f6d0-17f8-4636-b9d1-ac781cbb1f9d.png)
